name: Package

on:
  push:
    branches: 
      - develop
    paths-ignore:
      - target/**
      - dist/**

  pull_request:
    branches:
      - develop
    paths-ignore:
      - target/**
      - dist/**

jobs:
  package:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Build with NPM and Create WAR file
        run: |
          npm config set legacy-peer-deps true
          npm install node-sass --force
          npm install --force
          npm run build-ci

      - name: Create WAR file
        run: jar -cvf 104ui.war -C dist .

      - name: Upload WAR file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Helpline104-UI
          path: 104ui.war
